# The name of the workflow
name: Deploy to Github Pages

# The trigger for the workflow
on:
  push:
    # Run the workflow on push to the main branch
    branches:
      - main

# Environment variables for the workflow
env:
  NODE_ENV: production

# Define a job for the workflow
jobs:
  build:
    # Run the job on the latest version of Ubuntu
    runs-on: ubuntu-latest

    # Define a list of steps for the job
    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Node.js v14 for the job
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    # Install the project dependencies
    - name: Install dependencies
      run: npm ci

    # Build the webpack project
    - name: Build project
      run: npm run build

    # Deploy the built files to Github Pages
    - name: Deploy to Github Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        # The branch to deploy to
        BRANCH: gh-pages
        # The folder containing the built files
        FOLDER: dist
